const test=require('node:test');const assert=require('node:assert/strict');const {EmailClient,GmailApiClient,isActionableEmail}=require('../email');
function fakeClient(){const messages=[{uid:1,envelope:{subject:'Newsletter',from:[{name:'News',address:'newsletter@example.com'}],date:'2026-09-29T10:00:00Z'}},{uid:2,envelope:{subject:'Please review this',from:[{name:'Boss',address:'boss@example.com'}],date:'2026-09-29T11:00:00Z'}}];return{connect:async()=>{},logout:async()=>{},getMailboxLock:async()=>({release(){}}),search:async()=>[1,2],fetchAll:async()=>messages,fetchOne:async(uid,q)=>q.bodyStructure?{uid,envelope:messages[1].envelope,bodyStructure:{type:'text/plain',part:'1',encoding:'7bit'}}:{uid,bodyParts:new Map([['1',Buffer.from('Hello David')]])}};}
test('email client is graceful when credentials are missing',async()=>{const client=new EmailClient({host:'imap.example.com',user:'',pass:''});assert.equal(client.isConfigured(),false);assert.deepEqual(await client.listUnread(),[]);});
test('email unread list is capped, newest first, and does not request bodies',async()=>{let bodyRequested=false;const client=new EmailClient({host:'imap.example.com',user:'u',pass:'p',createClient:()=>{const fake=fakeClient();const original=fake.fetchAll;fake.fetchAll=async(u,q,o)=>{bodyRequested=Boolean(q.source||q.bodyParts);return original(u,q,o);};return fake;}});const messages=await client.listUnread(1);assert.equal(messages.length,1);assert.equal(messages[0].uid,2);assert.equal(bodyRequested,false);});
test('email read fetches only the plain-text body part',async()=>{let requestedParts=null;const client=new EmailClient({host:'imap.example.com',user:'u',pass:'p',createClient:()=>{const fake=fakeClient();const original=fake.fetchOne;fake.fetchOne=async(uid,q,o)=>{if(q.bodyParts)requestedParts=q.bodyParts;return original(uid,q,o);};return fake;}});const message=await client.read(2);assert.deepEqual(requestedParts,['1']);assert.equal(message.body,'Hello David');});
test('actionable email filtering excludes newsletters and automated senders',()=>{assert.equal(isActionableEmail({senderAddress:'newsletter@example.com',subject:'Weekly digest'}),false);assert.equal(isActionableEmail({senderAddress:'boss@example.com',subject:'Please review this'}),true);});

test('email client can authenticate with an OAuth access token',async()=>{let seen=null;const client=new EmailClient({host:'imap.gmail.com',user:'work@example.com',getAccessToken:async()=>'oauth-token',createClient:opts=>{seen=opts;return fakeClient();}});assert.equal(client.isConfigured(),true);await client.listUnread(1);assert.equal(seen.accessToken,'oauth-token');assert.equal(seen.pass,'');});

test('real ImapFlow config forces XOAUTH2 when OAuth token is present',async()=>{let config=null;class FakeFlow{constructor(opts){config=opts;}async connect(){}async getMailboxLock(){return{release(){}}}async search(){return[]}async logout(){}}const client=new EmailClient({host:'imap.gmail.com',user:'work@example.com',getAccessToken:async()=>'oauth-token',ImapFlowClass:FakeFlow});await client.listUnread(1);assert.equal(config.auth.accessToken,'oauth-token');assert.equal(config.auth.method,'XOAUTH2');assert.equal(config.auth.pass,undefined);});

test('Gmail API client reads unread metadata with readonly REST calls',async()=>{const calls=[];const responses=[{messages:[{id:'abc'}]},{id:'abc',snippet:'hello',payload:{headers:[{name:'From',value:'Boss <boss@example.com>'},{name:'Subject',value:'Review this'},{name:'Date',value:'Wed, 30 Sep 2026 10:00:00 -0500'}]}}];const fetchFn=async(url,opts)=>{calls.push({url,opts});return{ok:true,json:async()=>responses.shift()};};const client=new GmailApiClient({user:'work@example.com',getAccessToken:async()=>'token',fetchFn});const rows=await client.listUnread(5);assert.equal(rows[0].uid,'abc');assert.equal(rows[0].subject,'Review this');assert.match(calls[0].url,/gmail\.googleapis\.com\/gmail\/v1\/users\/me\/messages/);assert.equal(calls[0].opts.headers.Authorization,'Bearer token');});
