const { ImapFlow } = require('imapflow');
const DEFAULTS=Object.freeze({yahoo:{host:'imap.mail.yahoo.com',port:993},gmail:{host:'imap.gmail.com',port:993}});
function senderText(addresses=[]){const first=addresses[0];if(!first)return null;return first.name?`${first.name} <${first.address||''}>`:(first.address||null);}
function findPlainTextPart(node,fallback=null){if(!node)return fallback;if(String(node.type||'').toLowerCase()==='text/plain'&&!node.disposition)return node.part||fallback;for(const child of node.childNodes||[]){const found=findPlainTextPart(child,fallback);if(found)return found;}return fallback;}
function decodeText(buffer,encoding){if(!buffer)return '';if(typeof buffer==='string')return buffer;const value=Buffer.from(buffer);const mode=String(encoding||'').toLowerCase();if(mode==='base64')return Buffer.from(value.toString().replace(/\s+/g,''),'base64').toString('utf8');if(mode==='quoted-printable')return value.toString('utf8').replace(/=\r?\n/g,'').replace(/=([0-9A-F]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16)));return value.toString('utf8');}
class EmailClient {
 constructor({host,port=993,user,pass,label,ImapFlowClass=ImapFlow,createClient=null,getAccessToken=null}={}){Object.assign(this,{host,port,user:user||'',pass:pass||'',label:label||'email',ImapFlowClass,createClient,getAccessToken});}
 isConfigured(){return Boolean(this.user&&(this.pass||this.getAccessToken));}
 async newClient(){const accessToken=this.getAccessToken?await this.getAccessToken():null;const auth=accessToken?{user:this.user,accessToken,method:'XOAUTH2'}:{user:this.user,pass:this.pass};return this.createClient?this.createClient({host:this.host,port:this.port,user:this.user,pass:this.pass,accessToken,label:this.label}):new this.ImapFlowClass({host:this.host,port:this.port,secure:true,auth,logger:false,connectionTimeout:10000,greetingTimeout:10000,socketTimeout:15000});}
 friendlyError(err){const auth=err?.authenticationFailed===true||/AUTHENTICATIONFAILED|AUTHORIZATIONFAILED|AUTHFAILED/i.test(String(err?.serverResponseCode||err?.code||err?.response||''));if(auth){const hint=this.label==='work Gmail'?(this.getAccessToken?'Work Gmail OAuth was authorized, but Google rejected the IMAP session. Confirm IMAP access is allowed for this Workspace account.':'Work Gmail password authentication failed. Connect Google OAuth in Jarvis instead of using a normal password.'):'Personal Yahoo authentication failed. Check the Yahoo address and generated app password in Render.';const e=new Error(hint);e.code='EMAIL_AUTHENTICATION_FAILED';return e;}return err;}
 async withInbox(fn){if(!this.isConfigured())return null;const client=await this.newClient();let lock;try{await client.connect();lock=await client.getMailboxLock('INBOX');return await fn(client);}catch(err){throw this.friendlyError(err);}finally{lock?.release();try{await client.logout();}catch{client.close?.();}}}
 async testConnection(){if(!this.isConfigured())return{connected:false,status:'not_configured'};try{await this.withInbox(async()=>true);return{connected:true,status:'connected'};}catch(err){const auth=err?.code==='EMAIL_AUTHENTICATION_FAILED'||err?.authenticationFailed===true||/AUTHENTICATIONFAILED|AUTHORIZATIONFAILED|AUTHFAILED/i.test(String(err?.serverResponseCode||err?.code||''));return{connected:false,status:auth?'authentication_failed':'connection_failed',message:auth?err.message:'Mailbox login or access failed. Check the credentials and try again.'};}}
 normalizeMessage(message){const e=message?.envelope||{};const subject=String(e.subject||'(No subject)').slice(0,300);return{uid:Number(message.uid),sender:senderText(e.from||[]),senderAddress:e.from?.[0]?.address||null,subject,date:e.date?new Date(e.date).toISOString():(e.internalDate?new Date(e.internalDate).toISOString():null),snippet:subject};}
 async listUnread(limit=10){const cap=Math.min(25,Math.max(1,Number(limit)||10));return(await this.withInbox(async client=>{const uids=await client.search({seen:false},{uid:true});if(!uids?.length)return[];const selected=uids.slice(-cap).reverse();const messages=await client.fetchAll(selected,{envelope:true},{uid:true});return messages.map(m=>this.normalizeMessage(m)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,cap);}))||[];}
 async search({sender=null,subject=null,keyword=null,limit=10}={}){const cap=Math.min(25,Math.max(1,Number(limit)||10));const criteria={};if(sender)criteria.from=String(sender).slice(0,200);if(subject)criteria.subject=String(subject).slice(0,200);if(keyword)criteria.body=String(keyword).slice(0,200);if(!Object.keys(criteria).length)criteria.all=true;return(await this.withInbox(async client=>{const uids=await client.search(criteria,{uid:true});if(!uids?.length)return[];const selected=uids.slice(-cap).reverse();const messages=await client.fetchAll(selected,{envelope:true},{uid:true});return messages.map(m=>this.normalizeMessage(m)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,cap);}))||[];}
 async read(uid){const numericUid=Number(uid);if(!Number.isInteger(numericUid)||numericUid<=0)throw new Error('Email message id must be a positive integer.');return(await this.withInbox(async client=>{const message=await client.fetchOne(numericUid,{envelope:true,bodyStructure:true},{uid:true});if(!message)return null;const part=findPlainTextPart(message.bodyStructure);const base={uid:numericUid,sender:senderText(message.envelope?.from||[]),subject:String(message.envelope?.subject||'(No subject)').slice(0,300),date:message.envelope?.date?new Date(message.envelope.date).toISOString():null};if(!part)return{...base,body:'No plain-text body is available for this message.'};const bodyMessage=await client.fetchOne(numericUid,{bodyParts:[part]},{uid:true,binary:true});const raw=bodyMessage?.bodyParts?.get(part);const findNode=n=>{if(!n)return null;if(n.part===part)return n;for(const child of n.childNodes||[]){const found=findNode(child);if(found)return found;}return null;};const body=decodeText(raw,findNode(message.bodyStructure)?.encoding).replace(/\0/g,'').trim().slice(0,12000);return{...base,body};}))||null;}
}
function buildEmailClientsFromEnv(ImapFlowClass=ImapFlow,{googleOAuth=null}={}){return{yahoo:new EmailClient({...DEFAULTS.yahoo,user:process.env.YAHOO_IMAP_USER,pass:process.env.YAHOO_IMAP_PASS,label:'personal Yahoo',ImapFlowClass}),gmail:new EmailClient({...DEFAULTS.gmail,user:process.env.GOOGLE_IMAP_USER,pass:googleOAuth?null:process.env.GOOGLE_IMAP_PASS,getAccessToken:googleOAuth?()=>googleOAuth.accessToken():null,label:'work Gmail',ImapFlowClass})};}
function isActionableEmail(message={}){const sender=String(message.senderAddress||'').toLowerCase();const subject=String(message.subject||'').toLowerCase();if(/no[-_]?reply|donotreply|do[-_]?not[-_]?reply|mailer-daemon|newsletter|marketing|promo|digest|notifications?@|updates?@/.test(sender))return false;if(/unsubscribe|newsletter|weekly digest|daily digest|promotion|receipt|order confirmation|shipping update/.test(subject))return false;return true;}
module.exports={EmailClient,buildEmailClientsFromEnv,isActionableEmail,findPlainTextPart,decodeText};