const { ImapFlow } = require('imapflow');
const DEFAULTS=Object.freeze({yahoo:{host:'imap.mail.yahoo.com',port:993},gmail:{host:'imap.gmail.com',port:993}});
function senderText(addresses=[]){const first=addresses[0];if(!first)return null;return first.name?`${first.name} <${first.address||''}>`:(first.address||null);}
function findPlainTextPart(node,fallback=null){if(!node)return fallback;if(String(node.type||'').toLowerCase()==='text/plain'&&!node.disposition)return node.part||fallback;for(const child of node.childNodes||[]){const found=findPlainTextPart(child,fallback);if(found)return found;}return fallback;}
function decodeText(buffer,encoding){if(!buffer)return '';if(typeof buffer==='string')return buffer;const value=Buffer.from(buffer);const mode=String(encoding||'').toLowerCase();if(mode==='base64')return Buffer.from(value.toString().replace(/\s+/g,''),'base64').toString('utf8');if(mode==='quoted-printable')return value.toString('utf8').replace(/=\r?\n/g,'').replace(/=([0-9A-F]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16)));return value.toString('utf8');}
class EmailClient {
 constructor({host,port=993,user,pass,label,ImapFlowClass=ImapFlow,createClient=null}={}){Object.assign(this,{host,port,user:user||'',pass:pass||'',label:label||'email',ImapFlowClass,createClient});}
 isConfigured(){return Boolean(this.user&&this.pass);}
 newClient(){return this.createClient?this.createClient({host:this.host,port:this.port,user:this.user,pass:this.pass,label:this.label}):new this.ImapFlowClass({host:this.host,port:this.port,secure:true,auth:{user:this.user,pass:this.pass},logger:false});}
 async withInbox(fn){if(!this.isConfigured())return null;const client=this.newClient();await client.connect();const lock=await client.getMailboxLock('INBOX');try{return await fn(client);}finally{lock.release();await client.logout().catch(()=>{});}}
 normalizeMessage(message){const e=message?.envelope||{};const subject=String(e.subject||'(No subject)').slice(0,300);return{uid:Number(message.uid),sender:senderText(e.from||[]),senderAddress:e.from?.[0]?.address||null,subject,date:e.date?new Date(e.date).toISOString():(e.internalDate?new Date(e.internalDate).toISOString():null),snippet:subject};}
 async listUnread(limit=10){const cap=Math.min(25,Math.max(1,Number(limit)||10));return(await this.withInbox(async client=>{const uids=await client.search({seen:false},{uid:true});if(!uids?.length)return[];const selected=uids.slice(-cap).reverse();const messages=await client.fetchAll(selected,{envelope:true},{uid:true});return messages.map(m=>this.normalizeMessage(m)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,cap);}))||[];}
 async search({sender=null,subject=null,keyword=null,limit=10}={}){const cap=Math.min(25,Math.max(1,Number(limit)||10));const criteria={};if(sender)criteria.from=String(sender).slice(0,200);if(subject)criteria.subject=String(subject).slice(0,200);if(keyword)criteria.body=String(keyword).slice(0,200);if(!Object.keys(criteria).length)criteria.all=true;return(await this.withInbox(async client=>{const uids=await client.search(criteria,{uid:true});if(!uids?.length)return[];const selected=uids.slice(-cap).reverse();const messages=await client.fetchAll(selected,{envelope:true},{uid:true});return messages.map(m=>this.normalizeMessage(m)).sort((a,b)=>new Date(b.date||0)-new Date(a.date||0)).slice(0,cap);}))||[];}
 async read(uid){const numericUid=Number(uid);if(!Number.isInteger(numericUid)||numericUid<=0)throw new Error('Email message id must be a positive integer.');return(await this.withInbox(async client=>{const message=await client.fetchOne(numericUid,{envelope:true,bodyStructure:true},{uid:true});if(!message)return null;const part=findPlainTextPart(message.bodyStructure);const base={uid:numericUid,sender:senderText(message.envelope?.from||[]),subject:String(message.envelope?.subject||'(No subject)').slice(0,300),date:message.envelope?.date?new Date(message.envelope.date).toISOString():null};if(!part)return{...base,body:'No plain-text body is available for this message.'};const bodyMessage=await client.fetchOne(numericUid,{bodyParts:[part]},{uid:true,binary:true});const raw=bodyMessage?.bodyParts?.get(part);const findNode=n=>{if(!n)return null;if(n.part===part)return n;for(const child of n.childNodes||[]){const found=findNode(child);if(found)return found;}return null;};const body=decodeText(raw,findNode(message.bodyStructure)?.encoding).replace(/\0/g,'').trim().slice(0,12000);return{...base,body};}))||null;}
}
function buildEmailClientsFromEnv(ImapFlowClass=ImapFlow){return{yahoo:new EmailClient({...DEFAULTS.yahoo,user:process.env.YAHOO_IMAP_USER,pass:process.env.YAHOO_IMAP_PASS,label:'personal Yahoo',ImapFlowClass}),gmail:new EmailClient({...DEFAULTS.gmail,user:process.env.GOOGLE_IMAP_USER,pass:process.env.GOOGLE_IMAP_PASS,label:'work Gmail',ImapFlowClass})};}
function isActionableEmail(message={}){const sender=String(message.senderAddress||'').toLowerCase();const subject=String(message.subject||'').toLowerCase();if(/no[-_]?reply|donotreply|do[-_]?not[-_]?reply|mailer-daemon|newsletter|marketing|promo|digest|notifications?@|updates?@/.test(sender))return false;if(/unsubscribe|newsletter|weekly digest|daily digest|promotion|receipt|order confirmation|shipping update/.test(subject))return false;return true;}
module.exports={EmailClient,buildEmailClientsFromEnv,isActionableEmail,findPlainTextPart,decodeText};