const { getQuote } = require('./market');const { getTickerNews }=require('./market-news');const { normalizeTicker }=require('./market-sentinel');const { getFundamentals }=require('./sec-fundamentals');
async function initOpportunityWatchDb(pool){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS market_opportunities(
 id BIGSERIAL PRIMARY KEY,ticker TEXT NOT NULL UNIQUE,thesis TEXT NULL,status TEXT NOT NULL DEFAULT 'researching' CHECK(status IN ('researching','watch','pass','owned')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_reviewed_at TIMESTAMPTZ NULL,last_research JSONB NOT NULL DEFAULT '{}'::jsonb)`);}
async function listOpportunities(pool){if(!pool)return[];const {rows}=await pool.query('SELECT id,ticker,thesis,status,created_at,updated_at,last_reviewed_at,last_research FROM market_opportunities ORDER BY updated_at DESC');return rows;}
async function addOpportunity(pool,input={}){const ticker=normalizeTicker(input.ticker);if(!ticker)return{ok:false,error:'Enter a valid ticker.'};const quote=await getQuote(ticker);if(!Number.isFinite(Number(quote.price)))return{ok:false,error:`I could not verify ${ticker}.`};const thesis=String(input.thesis||'').trim().slice(0,600)||null;const {rows}=await pool.query(`INSERT INTO market_opportunities(ticker,thesis) VALUES($1,$2) ON CONFLICT(ticker) DO UPDATE SET thesis=COALESCE(EXCLUDED.thesis,market_opportunities.thesis),updated_at=NOW() RETURNING *`,[ticker,thesis]);return{ok:true,opportunity:rows[0],quote};}
async function updateOpportunity(pool,ticker,input={}){const key=normalizeTicker(ticker);const allowed=new Set(['researching','watch','pass','owned']);const status=String(input.status||'');if(!key||!allowed.has(status))return{ok:false,error:'Invalid ticker or status.'};const {rows}=await pool.query('UPDATE market_opportunities SET status=$1,updated_at=NOW() WHERE ticker=$2 RETURNING *',[status,key]);return rows[0]?{ok:true,opportunity:rows[0]}:{ok:false,error:'Opportunity not found.'};}
async function researchOpportunity(pool,ticker){const key=normalizeTicker(ticker);if(!key)return{ok:false,error:'Invalid ticker.'};const found=await pool.query('SELECT * FROM market_opportunities WHERE ticker=$1',[key]);if(!found.rows[0])return{ok:false,error:'Add the ticker to Opportunity Watch first.'};const [quote,headlines,fundamentals]=await Promise.all([getQuote(key),getTickerNews(key,10).catch(()=>[]),getFundamentals(key).catch(err=>({available:false,reason:err.message}))]);
 const research={ticker:key,asOf:new Date().toISOString(),price:quote.price,changePct:quote.changePct,source:quote.source,thesis:found.rows[0].thesis||null,headlines:headlines.slice(0,10),framework:{
  businessQuality:fundamentals.available?{netMarginPct:fundamentals.metrics.netMarginPct}: 'fundamentals unavailable',cashGeneration:fundamentals.available?{operatingCash:fundamentals.metrics.operatingCash,freeCashFlow:fundamentals.metrics.freeCashFlow}:'fundamentals unavailable',balanceSheet:fundamentals.available?{assets:fundamentals.metrics.assets,liabilities:fundamentals.metrics.liabilities,cash:fundamentals.metrics.cash,debt:fundamentals.metrics.debt}:'fundamentals unavailable',growth:fundamentals.available?{revenue:fundamentals.metrics.revenue,revenueGrowthPct:fundamentals.metrics.revenueGrowthPct}:'fundamentals unavailable',valuation:'needs market-cap/share-count data before claiming valuation',portfolioFit:'needs current portfolio',risks:'review filings and current news'},fundamentals,decision:fundamentals.available?'fundamentals-loaded':'research-incomplete'};
 await pool.query('UPDATE market_opportunities SET last_reviewed_at=NOW(),last_research=$1,updated_at=NOW() WHERE ticker=$2',[JSON.stringify(research),key]);return{ok:true,research};}
module.exports={initOpportunityWatchDb,listOpportunities,addOpportunity,updateOpportunity,researchOpportunity};