const { getQuote } = require('./market');const { getPortfolioSummary }=require('./portfolio');const { getSecFundamentals }=require('./sec-fundamentals');const { getTickerNews }=require('./market-news');const { normalizeTicker }=require('./market-sentinel');
async function initOpportunityWatchDb(pool){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS market_opportunities(
 id BIGSERIAL PRIMARY KEY,ticker TEXT NOT NULL UNIQUE,thesis TEXT NULL,status TEXT NOT NULL DEFAULT 'researching' CHECK(status IN ('researching','watch','pass','owned')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_reviewed_at TIMESTAMPTZ NULL,last_research JSONB NOT NULL DEFAULT '{}'::jsonb)`);}
async function listOpportunities(pool){if(!pool)return[];const {rows}=await pool.query('SELECT id,ticker,thesis,status,created_at,updated_at,last_reviewed_at,last_research FROM market_opportunities ORDER BY updated_at DESC');return rows;}
async function addOpportunity(pool,input={}){const ticker=normalizeTicker(input.ticker);if(!ticker)return{ok:false,error:'Enter a valid ticker.'};const quote=await getQuote(ticker);if(!Number.isFinite(Number(quote.price)))return{ok:false,error:`I could not verify ${ticker}.`};const thesis=String(input.thesis||'').trim().slice(0,600)||null;const {rows}=await pool.query(`INSERT INTO market_opportunities(ticker,thesis) VALUES($1,$2) ON CONFLICT(ticker) DO UPDATE SET thesis=COALESCE(EXCLUDED.thesis,market_opportunities.thesis),updated_at=NOW() RETURNING *`,[ticker,thesis]);return{ok:true,opportunity:rows[0],quote};}
async function updateOpportunity(pool,ticker,input={}){const key=normalizeTicker(ticker);const allowed=new Set(['researching','watch','pass','owned']);const status=String(input.status||'');if(!key||!allowed.has(status))return{ok:false,error:'Invalid ticker or status.'};const {rows}=await pool.query('UPDATE market_opportunities SET status=$1,updated_at=NOW() WHERE ticker=$2 RETURNING *',[status,key]);return rows[0]?{ok:true,opportunity:rows[0]}:{ok:false,error:'Opportunity not found.'};}
async function researchOpportunity(pool,ticker){const key=normalizeTicker(ticker);if(!key)return{ok:false,error:'Invalid ticker.'};const found=await pool.query('SELECT * FROM market_opportunities WHERE ticker=$1',[key]);if(!found.rows[0])return{ok:false,error:'Add the ticker to Opportunity Watch first.'};const [quote,headlines,fundamentals,portfolio]=await Promise.all([getQuote(key),getTickerNews(key,10).catch(()=>[]),getSecFundamentals(key).catch(err=>({available:false,reason:err.message})),getPortfolioSummary(pool).catch(()=>({totalValue:0,holdings:[]}))]);
 const margin=fundamentals.available&&fundamentals.revenue?.value?fundamentals.netIncome?.value/fundamentals.revenue.value*100:null;
 const shares=fundamentals.trends?.shares?.at(-1)?.value??null;const marketCap=Number.isFinite(Number(shares))&&Number.isFinite(Number(quote.price))?shares*Number(quote.price):null;
 const pe=marketCap&&fundamentals.netIncome?.value>0?marketCap/fundamentals.netIncome.value:null;const pFcf=marketCap&&fundamentals.freeCashFlow>0?marketCap/fundamentals.freeCashFlow:null;
 const existing=portfolio.holdings?.filter(h=>h.ticker===key)||[];const existingValue=existing.reduce((a,h)=>a+(Number(h.value)||0),0);const existingAllocation=portfolio.totalValue?existingValue/portfolio.totalValue*100:0;
 const research={ticker:key,asOf:new Date().toISOString(),price:quote.price,changePct:quote.changePct,source:quote.source,thesis:found.rows[0].thesis||null,headlines:headlines.slice(0,10),fundamentals,framework:{
  businessQuality:margin==null?'insufficient SEC data':{netMarginPct:Number(margin.toFixed(2)),evidence:'SEC annual revenue and net income'},
  cashGeneration:fundamentals.available?{operatingCashFlow:fundamentals.operatingCashFlow?.value??null,freeCashFlow:fundamentals.freeCashFlow??null,evidence:'SEC annual cash-flow facts'}:'SEC data unavailable',
  balanceSheet:fundamentals.available?{cash:fundamentals.cash?.value??null,assets:fundamentals.assets?.value??null,liabilities:fundamentals.liabilities?.value??null,equity:fundamentals.equity?.value??null,debt:fundamentals.debt?.value??null,evidence:'SEC annual balance-sheet facts'}:'SEC data unavailable',
  growth:fundamentals.available?{revenueCagrPct:fundamentals.trends?.revenueCagrPct??null,netIncomeCagrPct:fundamentals.trends?.netIncomeCagrPct??null,operatingCashFlowCagrPct:fundamentals.trends?.operatingCashFlowCagrPct??null,annualRevenue:fundamentals.trends?.revenue||[],annualNetIncome:fundamentals.trends?.netIncome||[],evidence:'SEC annual 10-K facts'}:'SEC data unavailable',
  valuation:{marketCap,peRatio:pe==null?null:Number(pe.toFixed(2)),priceToFreeCashFlow:pFcf==null?null:Number(pFcf.toFixed(2)),sharesUsed:shares,priceUsed:quote.price,note:'Descriptive multiples only; no cheap/expensive conclusion without a benchmark.'},
  portfolioFit:{portfolioValue:portfolio.totalValue||0,alreadyOwned:existing.length>0,currentValue:existingValue,currentAllocationPct:Number(existingAllocation.toFixed(2)),note:portfolio.totalValue?'Current concentration context only; not a target allocation.':'Portfolio holdings unavailable, so fit cannot be assessed.'},
  risks:'review filings and current news'},decision:fundamentals.available?'research-ready':'research-incomplete'};
 await pool.query('UPDATE market_opportunities SET last_reviewed_at=NOW(),last_research=$1,updated_at=NOW() WHERE ticker=$2',[JSON.stringify(research),key]);return{ok:true,research};}
module.exports={initOpportunityWatchDb,listOpportunities,addOpportunity,updateOpportunity,researchOpportunity};