const test=require('node:test');const assert=require('node:assert/strict');const {collectProactiveSignals,runProactiveCheck}=require('../proactive-agent');

test('proactive signals stay silent for routine context',()=>{assert.deepEqual(collectProactiveSignals({priorityContext:{approvals:[],market:{material:[]},email:{yahoo:[],gmail:[]}}}),[])});

test('proactive signals elevate security email',()=>{const s=collectProactiveSignals({priorityContext:{approvals:[],market:{material:[]},email:{yahoo:[{subject:'Urgent: confirm this purchase attempt'}],gmail:[]}}});assert.equal(s[0].kind,'email');});

test('proactive check deduplicates an already notified state',async()=>{const queries=[];const pool={query:async(sql,args)=>{queries.push([sql,args]);if(sql.startsWith('SELECT'))return{rows:[{attention_key:require('../proactive-agent').signalKey([{kind:'email',priority:95,title:'Security alert',detail:'A recent message appears to require prompt verification or action.'}]),notification_sent:true}]};return{rows:[]}}};const context={priorityContext:{approvals:[],market:{material:[]},email:{yahoo:[{subject:'Security alert'}],gmail:[]}}};let sent=0;const r=await runProactiveCheck({pool,getContext:async()=>context,notify:async()=>{sent++}});assert.equal(r.notify,false);assert.equal(sent,0);});


test('proactive intelligence ignores handled security email',()=>{const s=collectProactiveSignals({priorityContext:{approvals:[],market:{material:[]},calendar:{personal:[],work:[]},email:{yahoo:[{subject:'Security alert',conversationState:'waiting_on_them'}],gmail:[]}}},new Date('2026-10-02T12:00:00Z'));assert.equal(s.length,0);});
test('proactive intelligence flags real calendar conflicts but ignores Busy blocks',()=>{const now=new Date('2026-10-02T12:00:00Z');const base={approvals:[],market:{material:[]},email:{yahoo:[],gmail:[]}};const real=collectProactiveSignals({priorityContext:{...base,calendar:{personal:[],work:[{title:'Interview',start:'2026-10-02T14:00:00Z',end:'2026-10-02T15:00:00Z'},{title:'Plant Review',start:'2026-10-02T14:30:00Z',end:'2026-10-02T15:30:00Z'}]}}},now);assert.ok(real.some(x=>x.kind==='calendar_conflict'));const busy=collectProactiveSignals({priorityContext:{...base,calendar:{personal:[],work:[{title:'Interview',start:'2026-10-02T14:00:00Z',end:'2026-10-02T15:00:00Z'},{title:'Busy',start:'2026-10-02T14:00:00Z',end:'2026-10-02T15:00:00Z'}]}}},now);assert.ok(!busy.some(x=>x.kind==='calendar_conflict'));});
test('proactive intelligence flags named event within 45 minutes',()=>{const s=collectProactiveSignals({priorityContext:{approvals:[],market:{material:[]},email:{yahoo:[],gmail:[]},calendar:{personal:[],work:[{title:'Interview',start:'2026-10-02T12:30:00Z',end:'2026-10-02T13:00:00Z'}]}}},new Date('2026-10-02T12:00:00Z'));assert.ok(s.some(x=>x.kind==='calendar_soon'));});
